### ISSUE TITLE
Question: Core in Erlang

### ISSUE THREAD

**Issue by fnchooft** [bitwalker/libgraph#35]
Good Morning Bitwalker,

First of all , a great job on the library.

One question: did you ever consider porting the libgraph-core to Erlang ??
I saw you are using some erlang-dependencies, but I do not have enough Elixir know-how to deduce how much effort would be needed or if it is possible at all.

Kind regards, and thanks for the library - which might well propel me into the direction of Elixir.

**Comment by bitwalker** [comment]
@fnchooft Hi! Thanks for the kind words!

I didn't explicitly consider it, but I have done that kind of thing before. That said, my usual preference for an Elixir library is to write an Erlang API that "wraps" the Elixir core, rather than rewrite the library in Erlang and wrap it in Elixir. Rewriting libgraph in Erlang is not something I'm opposed to, but would be a fair bit of work - given my time constraints these days, I'd be pretty reliant on the community to make it happen. Part of the reason I wrote it in Elixir, rather than Erlang, is due to the greater expressive power of the language, which made it a lot faster to write, and makes for easier maintenance, as well as a larger number of contributions generally speaking. But I don't think any of the code is dependent on Elixir, so it is certainly possible.
